import { Question } from "./types";

export const chapter1Questions: Question[] = [
    { id: 1, text: "Plaster of Paris is obtained by calcining", options: { a: "gypsum", b: "calcium oxide", c: "calcium carbonate", d: "quick lime" }, answer: "a" },
    { id: 2, text: "For repetitive use, formworks in concrete construction, what material is preferred", options: { a: "stone", b: "steel", c: "timber", d: "bamboo" }, answer: "b" },
    { id: 3, text: "Early strength of cement is due to which compound", options: { a: "C3S", b: "C₂S", c: "C3A", d: "CAF" }, answer: "a" },
    { id: 4, text: "Why are bricks soaked in water before using the brick masonry?", options: { a: "To wash dust", b: "To prevent moisture loss from mortar", c: "For even spreading of mortar", d: "All of the above" }, answer: "d" },
    { id: 5, text: "The arrangement made to support an unsafe structure temporarily is known as", options: { a: "underpinning", b: "scaffolding", c: "shoring", d: "jacking" }, answer: "c" },
    { id: 6, text: "Before plastering, the surface has to be", options: { a: "rough", b: "smooth", c: "cemented", d: "watered" }, answer: "a" },
    { id: 7, text: "The drawback of electric seasoning of timber is", options: { a: "splitting", b: "cracking", c: "rot", d: "checks" }, answer: "a" },
    { id: 8, text: "What is the composition of quartzite?", options: { a: "Calcareous", b: "Siliceous", c: "Argillaceous", d: "None of the above" }, answer: "b" },
    { id: 9, text: "The component of paint that imparts color to it is called", options: { a: "pigment", b: "vehicle", c: "both (a) and (b)", d: "none of the above" }, answer: "a" },
    { id: 10, text: "Which lime is used in lime motor?", options: { a: "Quick lime", b: "Fat lime", c: "Hydraulic lime", d: "Limp lime" }, answer: "c" },
    { id: 11, text: "Which of the following is primary raw material in the cement manufacturing?", options: { a: "Mica", b: "Limestone", c: "Aluminum", d: "Coal" }, answer: "b" },
    { id: 12, text: "Lacquer is", options: { a: "Oil paints", b: "Distempér", c: "Spirit Varnish", d: "Enamel paints" }, answer: "c" },
    { id: 13, text: "The initial setting time of ordinary Portland cement is", options: { a: "10 minutes", b: "30 minutes", c: "6 hours", d: "10 hours" }, answer: "b" },
    { id: 14, text: "The presence of sand in brick earth prevents", options: { a: "cracking of bricks", b: "shrinkage of bricks", c: "warping of bricks", d: "none of the above" }, answer: "c" },
    { id: 15, text: "The seasoning of timber is done for", options: { a: "increasing moisture content", b: "decreasing moisture content", c: "reducing knots", d: "determining age of the timber" }, answer: "b" },
    { id: 16, text: "Plastic bitumen is generally used for", options: { a: "road pavements", b: "expansion joints", c: "crack fillings", d: "none of the above" }, answer: "c" },
    { id: 17, text: "What are the main compounds resulting from cement hydration?", options: { a: "C3S", b: "CSA", c: "CSHA", d: "CSH Gel" }, answer: "d" },
    { id: 18, text: "The indentation surface of the brick is called", options: { a: "frog", b: "shiner", c: "header", d: "shoulder" }, answer: "a" },
    { id: 19, text: "The minimum density of medium-density fiberboard is", options: { a: "500 to 600 kg/m³", b: "600 to 800 kg/m³", c: "800 to 1000 kg/m³", d: "1000 to 1200 kg/m³" }, answer: "b" },
    { id: 20, text: "The construction material that can be obtained from naturally existing rock by any method is", options: { a: "brick", b: "stone", c: "steel", d: "timber" }, answer: "b" },
    { id: 21, text: "The type of cement used for painting is", options: { a: "quick setting cement", b: "white cement", c: "rapid hardening", d: "ordinary Portland cement" }, answer: "b" },
    { id: 22, text: "Which of the following type of aggregate is not available in Nepal?", options: { a: "Basalt", b: "Sandstone", c: "Limestone", d: "Granite" }, answer: "a" },
    { id: 23, text: "Which technique is primarily used for sealing cracks in asphalt pavement?", options: { a: "Fog sealing", b: "Overlay", c: "Thermal sealing", d: "Crack filling" }, answer: "d" },
    { id: 24, text: "After storage, the strength of cement is", options: { a: "decreases", b: "increases", c: "remains same", d: "may increase or decrease" }, answer: "a" },
    { id: 25, text: "Which one of the following is incorrect regarding plasticizer?", options: { a: "Used for flowing mortar in heavy dam", b: "Increases strength with reduction in water and increasing cement", c: "Acts as both reducers and retarder", d: "Enhances workability without affecting strength" }, answer: "c" },
    { id: 26, text: "Metallurgy is the process of.............", options: { a: "roasting the ore", b: "extracting metals from the ore", c: "extracting minerals from the ore", d: "adding carbon to the ore in blast furnace" }, answer: "b" },
    { id: 27, text: "Addition of gypsum to cement is", options: { a: "reduces setting time of cement", b: "increases setting time of cement", c: "produces very light color cement", d: "shining surface is formed" }, answer: "c" },
    { id: 28, text: "Removal of impurities from ore is known as", options: { a: "crushing", b: "concentration of ore", c: "washing", d: "grinding" }, answer: "b" },
    { id: 29, text: "The pigment used in paints for corrosive resistance, is", options: { a: "white lead-", b: "ferrous oxide", c: "zinc white", d: "red lead" }, answer: "d" },
    { id: 30, text: "Which of the following ingredients imparts red color to the clay bricks?", options: { a: "Silica", b: "Iron oxide", c: "Lime", d: "Aluminum" }, answer: "b" },
    { id: 31, text: "Which of the following is not a type of hydraulic cement?", options: { a: "Ordinary portland cement", b: "Portland pozzolana cement", c: "Portland slag cement", d: "Hydration of lime" }, answer: "d" },
    { id: 32, text: "The operation of removal of impurities of clay adhering to iron ore is known as", options: { a: "calcination", b: "purification", c: "dressing", d: "refining" }, answer: "c" },
    { id: 33, text: "Swelling in brick is also known as", options: { a: "chuff", b: "bloating", c: "effloresce", d: "lamination" }, answer: "b" },
    { id: 34, text: "The process of cement hydration involves", options: { a: "drying of cement", b: "evaporation of water", c: "mixing with water to form a paste", d: "freezing of cement" }, answer: "b" },
    { id: 35, text: "The property of the material that enables it to be drawn out or elongated to an appreciable extent is called", options: { a: "malleability", b: "ductility", c: "brittle", d: "plasticity" }, answer: "b" },
    { id: 36, text: "The main alloying element in stainless steel is", options: { a: "nickel", b: "carbon", c: "vanadium", d: "chromium" }, answer: "d" },
    { id: 37, text: "The percentage of carbon content present in steel is", options: { a: "0.06% to 0.15%", b: "0.15% to 1.5%", c: "1.5% to 3.5%", d: "greater than 2.5%" }, answer: "b" },
    { id: 38, text: "Compressive strength of 1st class brick is", options: { a: "> 10.5", b: ">7", c: "> 3.5", d: "<3.5" }, answer: "a" },
    { id: 39, text: "Vicat apparatus is used in", options: { a: "consistency test", b: "compressive strength test", c: "soundness test", d: "fineness of cement" }, answer: "a" },
    { id: 40, text: "For 1 class bricks, the water absorption should not be more than", options: { a: "10%", b: "15%", c: "20%", d: "30%" }, answer: "b" },
    { id: 41, text: "For a compressive test of brick which of the following mortar ratio is placed in the frog?", options: { a: "1:1", b: "1:2", c: "1:3", d: "1:4" }, answer: "a" },
    { id: 42, text: "In compressive strength test, the minimum strength developed by the cube of M20 cement concrete in 7 days is", options: { a: "10 MPa", b: "12.5 MPa", c: "15 MPa", d: "20 MPa" }, answer: "b" },
    { id: 43, text: "Which of the following is not the type of non-destructive test?", options: { a: "Compression test", b: "Visual testing", c: "Ultrasonic testing.", d: "Eddy current testing" }, answer: "a" },
    { id: 44, text: "Soundness of cement is done by the apparatus of", options: { a: "slump cone", b: "Le-Chatelier", c: "Vicat's needle", d: "UTM" }, answer: "b" },
    { id: 45, text: "Le-Chatelier's apparatus is used for which type of test?", options: { a: "Soundness test", b: "Consistency test", c: "Hardness test", d: "Abrasion test" }, answer: "a" },
    { id: 46, text: "Terracotta is used in buildings for", options: { a: "ornamental work", b: "insulation", c: "storage", d: "none of the above" }, answer: "a" },
    { id: 47, text: "is prepared on the basis of plinth area of the building, the rate being deducted from the cost of a similar building having similar specifications, heights, and construction in the locality.", options: { a: "Cube rate estimate", b: "Supplementary estimate", c: "Maintenance estimate", d: "Plinth area estimate" }, answer: "d" },
    { id: 48, text: "The number of treads in a flight is equal to", options: { a: "risers in the flight", b: "risers plus one", c: "risers minus one", d: "risers plus three" }, answer: "c" },
    { id: 49, text: "Which is the weakest bond in building?", options: { a: "Flemish bond", b: "English bond", c: "Raking bond", d: "Header bond" }, answer: "c" },
    { id: 50, text: "In case of cavity walls where both walls are load bearing the effective thickness is", options: { a: "sum of both walls", b: "thickness of stronger wall", c: "of 2/3 of sum of thickness of both walls", d: "larger of (b) and (c)" }, answer: "d" },
    { id: 51, text: "What is the purpose of providing waterproof tiles?", options: { a: "Help to reduce fire catch", b: "Provide smooth surface", c: "Help in sound insulation", d: "Prevents water from entering" }, answer: "d" },
    { id: 52, text: "What is used in rainwater gutter in roof?", options: { a: "Cement", b: "Sand", c: "Bitumen", d: "All of the above" }, answer: "d" },
    { id: 53, text: "A projecting piece usually provided to support a truss, is", options: { a: "cornice", b: "coping", c: "frieze", d: "lintel" }, answer: "c" },
    { id: 54, text: "The process of making the back ground rough, before plastering, is", options: { a: "dubbing", b: "hacking", c: "blistering", d: "peeling" }, answer: "b" },
    { id: 55, text: "Which of the below utilities cannot be provided underneath a floor?", options: { a: "Plumbing", b: "Air conditioning", c: "Gas pipe", d: "Thermal proofing" }, answer: "c" },
    { id: 56, text: "The carpet area of residential building is percentage of plinth area.", options: { a: "20-30%", b: "30-50%", c: "50-65%", d: "65-75%" }, answer: "c" },
    { id: 57, text: "As per regulations, the plinth area should have occupied about of total plot area.", options: { a: "50 to 60%", b: "20 to 30%", c: "40 to 50%", d: "60 to 75%" }, answer: "d" },
    { id: 58, text: "The type of stone used for the construction of retaining walls must be", options: { a: "soft", b: "hard", c: "light", d: "heavy" }, answer: "d" },
    { id: 59, text: "The dressing of stone is done", options: { a: "immediately after quarrying", b: "after seasoning", c: "after three months of quarrying", d: "just before construction" }, answer: "a" },
    { id: 60, text: "Which of the following relation is/are correct?", options: { a: "Floor area = Plinth area + Area of wall", b: "Plinth area = Carpet area + Circulation area + Wall area", c: "Built up area = Plot area + Setback area", d: "All of the above" }, answer: "b" },
    { id: 61, text: "Where is circular finishing commonly applied in construction?", options: { a: "Columns", b: "Pillars", c: "Roofs", d: "Walls" }, answer: "b" },
    { id: 62, text: "Find the distance to the centroid of the channel section shown in figure, from the left edge (Web 200x10mm, Flanges 100x10mm).", options: { a: "10.53 mm", b: "57.36 mm", c: "21.07 mm", d: "28.68 mm" }, answer: "d" },
    { id: 63, text: "In which of the following, CG and geometric center doesn't coincide.", options: { a: "Circle", b: "Triangle", c: "Rectangle", d: "Right angle triangle" }, answer: "d" },
    { id: 64, text: "Second moment of area of triangle about its base is", options: { a: "I = bh³/36", b: "I = bh³/24", c: "I = bh³/12", d: "I = bh³/6" }, answer: "c" },
    { id: 65, text: "The angle for well conditional triangle should not be less than", options: { a: "60 degree", b: "45 degree", c: "20 degree", d: "30 degree" }, answer: "d" },
    { id: 66, text: "Section modulus of a hollow circular section is", options: { a: "Z = π(D⁴-d⁴)/30D", b: "Z = π(D⁴-d⁴)/32D", c: "Z = π(D⁴-d⁴)/16D", d: "Z = π(D²-d²)/32D" }, answer: "b" },
    { id: 67, text: "MOI of inertia of hollow circular section is", options: { a: "π/8 × (R⁴-r⁴)", b: "π/16 × (R⁴-r⁴)", c: "π/4 × (R⁴-r⁴)", d: "π/64 × (R⁴-r⁴)" }, answer: "c" },
    { id: 68, text: "What is the section modulus of circular section?", options: { a: "πd²/16", b: "πd³/16", c: "πd³/32", d: "πd³/64" }, answer: "c" },
    { id: 69, text: "What is the moment of inertia of a rectangular section about a horizontal axis passing through the base?", options: { a: "bd³/12", b: "bd³/6", c: "bd³/3", d: "bd²/3" }, answer: "c" },
    { id: 70, text: "The CG of a cone from its base is", options: { a: "h/3", b: "h/4", c: "h/2", d: "3h/4" }, answer: "b" },
    { id: 71, text: "Calculate the second moment of area of a hollow circular section with external and internal diameter 20 cm and 10 cm respectively.", options: { a: "2347 cm⁴", b: "3681 cm⁴", c: "7363 cm⁴", d: "9375 cm⁴" }, answer: "c" },
    { id: 72, text: "The perpendicular axis theorem is used to calculate the MOI of", options: { a: "circular lamina", b: "semi-circular lamina", c: "triangle lamina", d: "square lamina" }, answer: "a" },
    { id: 73, text: "Moment of inertia of rectangle about CG with axis parallel to X-axis is", options: { a: "bd³/12", b: "db³/12", c: "bd³/3", d: "db³/3" }, answer: "a" },
    { id: 74, text: "Center of gravity of hemisphere is", options: { a: "4r/3", b: "4r/5", c: "3r/8", d: "5r/3" }, answer: "d" },
    { id: 75, text: "A solid having equilateral triangle as base and other faces converging towards its axis is known as", options: { a: "prism", b: "pyramid", c: "hexahedron", d: "cone" }, answer: "b" },
    { id: 76, text: "Which of the following shape is made up of uniform triangles?", options: { a: "Cone", b: "Prism", c: "Pyramid", d: "None of the above" }, answer: "b" },
    { id: 77, text: "The radius of gyration of a rectangular section is not proportional to", options: { a: "square root of the moment of inertia", b: "square root of the inverse of the area", c: "square root of the moment of inertia divided by area of the section", d: "none of the above" }, answer: "d" },
    { id: 78, text: "Moment of inertia of a triangular section of base and height about an axis passing through its vertex and parallel to the base is ... than that passing through its CG and parallel to the base.", options: { a: "2 times", b: "3 times", c: "6 times", d: "9 times" }, answer: "d" },
    { id: 79, text: "What is the MOI of semi-circle about base?", options: { a: "πR⁴/8", b: "πR⁴/16", c: "πR⁴/32", d: "πR⁴/128" }, answer: "a" },
    { id: 80, text: "MOI of semicircle about the base is", options: { a: "πD⁴/128", b: "πD⁴/16", c: "πD⁴/64", d: "πD⁴/32" }, answer: "a" },
    { id: 81, text: "The moment of inertia of the circle is", options: { a: "πd⁴/64", b: "πd⁴/32", c: "πd⁴/16", d: "πd³/64" }, answer: "a" },
    { id: 82, text: "The moment of inertia through centroid of triangle parallel to base is", options: { a: "bd³/3", b: "bd³/12", c: "bd³/36", d: "bd³/72" }, answer: "c" },
    { id: 83, text: "The area moment of inertia of a semi-circular region having diameter 'd' about its diametric axis is", options: { a: "πd²/36", b: "πd²/128", c: "πd⁴/128", d: "πd⁴/64" }, answer: "c" },
    { id: 84, text: "The CG of solid hemisphere lies at the distance ... from base.", options: { a: "3r/2", b: "3r/4", c: "3r/5", d: "3r/8" }, answer: "d" },
    { id: 85, text: "The moment of inertia of hollow rectangular section having outer depth 'D' and breadth 'B' and dimensions of inner rectangle are depth 'd' and width 'b' about horizontal axis passing through the Centroid is", options: { a: "BD³/12", b: "bd³/12", c: "BD³-bd³/12", d: "BD²-bd²/12" }, answer: "c" },
    { id: 86, text: "What is the shape factor of rectangular section?", options: { a: "1.4", b: "1.5", c: "1.2", d: "2" }, answer: "b" },
    { id: 87, text: "What is the formula of radius of gyration?", options: { a: "k² = I/A", b: "k² = I²/A", c: "k² = I²/A²", d: "k² = (I/A)^1/2" }, answer: "a" },
    { id: 88, text: "What is the MOI of rectangular section about the base?", options: { a: "BD³/12", b: "bd³/4", c: "bd³/3", d: "bd³/36" }, answer: "a" },
    { id: 89, text: "The section modulus of hollow circular section having external diameter D and internal diameter d is", options: { a: "π(D⁴-d⁴)/64D", b: "π(D⁴-d⁴)/32D", c: "π(D³-d³)/32D", d: "π(D³-d³)/64D" }, answer: "b" },
    { id: 90, text: "Find the centroid of T section. [Figure: Top flange width=120 mm, Bottom (web)=30 mm, Thickness of flange=30mm depth of web=100 mm]", options: { a: "63 mm", b: "85.4 mm", c: "112.5 mm", d: "None of the above" }, answer: "b" },
    { id: 91, text: "A trapezoid having two parallel side 'a' and 'b' and height 'h'. The Y centroid distance from bottom side 'b' is", options: { a: "0.5 H[(b+2a)/(b+a)]", b: "0.5 [(b-2a)/(b+a)]", c: "H/3 × [(b+2a)/(b+a)]", d: "H/3 × [(b-2a)/(b+a)]" }, answer: "c" },
    { id: 92, text: "Calculate the location of the centroid of the L section shown in figure (100x100x8mm unequal leg profile notation dynamic context)", options: { a: "28 mm, 28 mm", b: "8 mm, 8 mm", c: "50 mm, 50 mm", d: "none of the above" }, answer: "a" },
    { id: 93, text: "If level is located at mid-point then which error is eliminated?", options: { a: "Cc", b: "Cr", c: "Both (a) and (b)", d: "none of the above" }, answer: "c" },
    { id: 94, text: "How many satellites are used for GPS by the US Department of Defense?", options: { a: "24", b: "18", c: "20", d: "22" }, answer: "a" },
    { id: 95, text: "What is the value of right face zenithal angle if left face zenithal angle is 98°30'30\"?", options: { a: "261°29'30\"", b: "178°30'30\"", c: "81°29'30\"", d: "98°30'30\"" }, answer: "a" },
    { id: 96, text: "Topography survey is done for ....", options: { a: "Soil", b: "Engineering", c: "Traffic", d: "All of the above" }, answer: "d" },
    { id: 97, text: "Which of the following doesn't determine the capability of GIS?", options: { a: "Defining a map", b: "Representing cartographic features", c: "Retrieving data", d: "Transferring data" }, answer: "d" },
    { id: 98, text: "Find the perpendicular distance if the radius of the curve is 10.26 m and the angle is 0 = 10°24'", options: { a: "0.042 m", b: "0.402 m", c: "0.204 m", d: "0.024 m" }, answer: "a" },
    { id: 99, text: "Which of the following indicates the formula for arithmetic check?", options: { a: "ΣB.S - ΣF.S = Last R.L - First R.L", b: "ΣF.S - ΣB.S = Last R.L - First R.L", c: "ΣB.S + ΣF.S = First R.L - Last R.L", d: "ΣF.S + ΣB.S = Last R.L - First R.L" }, answer: "a" },
    { id: 100, text: "Find the value of radius of curvature if D is given as 23.76.", options: { a: "241.16 m", b: "214.16 m", c: "271.23 m", d: "217.23 m" }, answer: "a" },
    { id: 101, text: "In closed traverse, the sum of the north latitudes is more than the sum of the south latitudes and also the sum of west departures is more than the sum of the east departures, the closing line lies is in", options: { a: "NE quadrant", b: "SE quadrant", c: "NW quadrant", d: "SW quadrant" }, answer: "c" },
    { id: 102, text: "Readings taken during traversing using total station are", options: { a: "horizontal angle, vertical angle, horizontal distance, vertical distance", b: "horizontal angle, vertical angle, horizontal distance, vertical distance, station height", c: "horizontal angle, vertical angle, horizontal distance, station height", d: "horizontal angle, horizontal distance, vertical distance, station height, height of instrument" }, answer: "d" },
    { id: 103, text: "The bearings of the lines AB and BC are 146° 30' and 68° 30' The included angle ABC is", options: { a: "102°", b: "78°", c: "45°", d: "none of the above" }, answer: "a" },
    { id: 104, text: "What is the direction of closing error?", options: { a: "tan δ = ΣL/ΣD", b: "tan δ = ΣL²/ΣD²", c: "tan δ = ΣD/ΣL", d: "tan δ = ΣD²/ΣL²" }, answer: "c" },
    { id: 105, text: "Which of following is obstacle to chaining but not for ranging?", options: { a: "Building", b: "Hillock", c: "River", d: "All of the above" }, answer: "c" },
    { id: 106, text: "The bench marks are fixed during the", options: { a: "preliminary survey", b: "reconnaissance", c: "detailed survey", d: "after detailed project report" }, answer: "c" },
    { id: 107, text: "Contour lines of different elevations can unite to form one line, only in the case of", options: { a: "a vertical cliff", b: "a saddle", c: "a water shed line", d: "a hill top" }, answer: "a" },
    { id: 108, text: "The magnetic bearing of a line is 32° and the magnetic declination is 10°15' W. The true bearing is", options: { a: "21°45'", b: "42°15'", c: "42°15'W", d: "21°45'W" }, answer: "a" },
    { id: 109, text: "The plan used to intercept drainage, surface conditions, and topography is called", options: { a: "detailed plan", b: "contour plan", c: "layout plan", d: "site plan" }, answer: "b" },
    { id: 110, text: "The first stage of the survey is", options: { a: "reconnaissance", b: "preliminary survey", c: "map study", d: "detailed survey" }, answer: "c" },
    { id: 111, text: "What kind of slope do closely space equal contour line indicates?", options: { a: "Gentle slope", b: "Steep slope", c: "Flat slope", d: "V-sloped" }, answer: "b" },
    { id: 112, text: "The dumpy level is most suitable for leveling survey is", options: { a: "on flat terrain", b: "in hilly areas", c: "on a steep slope", d: "in forest areas" }, answer: "a" },
    { id: 113, text: "Which method of levelling is generally adopted if there are lot many numbers of intermediate stations?", options: { a: "Rise and fall method", b: "Height of instrument method", c: "Collimation method", d: "Both (b) and (c)" }, answer: "d" },
    { id: 114, text: "The formula to calculate elevation in tachometric surveying is", options: { a: "KS sin 2θ - C cos θ", b: "KS sin θ - C cos θ", c: "KS sin θ + C cos θ", d: "KS sin 2θ / 2 + C sin θ" }, answer: "d" },
    { id: 115, text: "For 1 m³ volume of 1: 1.5: 3 PCC how many bags of cement are required?", options: { a: "6 bags", b: "7 bags", c: "8 bags", d: "9 bags" }, answer: "c" },
    { id: 116, text: "Binding wire quantity in 1 quintal reinforcement is", options: { a: "1 kg", b: "5 kg", c: "2 kg", d: "10 kg" }, answer: "a" },
    { id: 117, text: "In long wall-short wall method, the length of the long wall is the sum of center line and", options: { a: "b/2", b: "b/4", c: "b", d: "2b" }, answer: "c" },
    { id: 118, text: "Given the carpet area of a floor is 100 m² and the circulation area is 50% of the plinth area, and the rate per sq. m of plinth area is Rs. 40,000. What is the total estimate of the building?", options: { a: "80 lakhs", b: "8 lakhs", c: "120 lakhs", d: "12 lakhs" }, answer: "a" },
    { id: 119, text: "The quantity of brickwork with mortar in foundation used per mason per day is", options: { a: "1.25 m³", b: "2.5 m³", c: "3.5 m³", d: "4.5 m³" }, answer: "a" },
    { id: 120, text: "The process of determining fair price or value of a property is known as", options: { a: "depreciation", b: "inflation", c: "valuation", d: "all of the above" }, answer: "c" },
    { id: 121, text: "Calculate the number of cement bag required if overall density is 2350 kg/m³, aggregate = 3860 kg, w/c=0.4 and volume of concrete = 2 m³", options: { a: "8 bags", b: "6 bags", c: "12 bags", d: "16 bags" }, answer: "c" },
    { id: 122, text: "Which of the following is not measure in cumes?", options: { a: "One and half brick wall", b: "Reinforced Brick works", c: "Brickwork in arches", d: "Half brick wall" }, answer: "d" },
    { id: 123, text: "If w/c=0.8, volume of cement is 2 m³ find the volume of water in liter?", options: { a: "1.6 liters", b: "160 liters", c: "1600 liters", d: "2300 liters" }, answer: "d" },
    { id: 124, text: "The expected out turn of the cement concrete 1:2:4 for per mason per will be", options: { a: "5.0 m³", b: "3.5 m³", c: "2.5 m³", d: "1.5 m³" }, answer: "a" },
    { id: 125, text: "The volume of cement in 50 kg bag is", options: { a: "0.0345 m³", b: "0.557 m³", c: "0.345 m³", d: "0.75 m³" }, answer: "a" },
    { id: 126, text: "Revised estimate is prepared when the original sanctioned estimate differs by more than", options: { a: "5%", b: "10%", c: "15%", d: "20%" }, answer: "a" },
    { id: 127, text: "For well triangle condition each angle shouldn't be less than?", options: { a: "15°", b: "30°", c: "45°", d: "60°" }, answer: "b" },
    { id: 128, text: "As per NBC, the standard size of brick is", options: { a: "230 mm×110 mm×55 mm", b: "240 mm×115 mm×57 mm", c: "240 mm×110 mm×55 mm", d: "230 mm×115 mm×57 mm" }, answer: "c" },
    { id: 129, text: "Calculate the MOI of section about axis passing through CG and parallel to base of an isosceles triangle section having width 80 mm and height 60 mm.", options: { a: "15×10⁶ mm⁴", b: "20×10⁶ mm⁴", c: "480×10³ mm⁴", d: "1440×10³ mm⁴" }, answer: "c" },
    { id: 130, text: "The surface dressing is measured in", options: { a: "sq. m", b: "cubic meter", c: "r. m", d: "metric ton" }, answer: "a" },
    { id: 131, text: "The MOI of hollow semi-circle having external diameter 200 mm and internal diameter of 120 mm about its base is ..... mm⁴.", options: { a: "34.1×10³", b: "34.2×10⁶", c: "34.3×10³", d: "68.36×10⁶" }, answer: "b" },
    { id: 132, text: "The size of brick is specified by", options: { a: "weight", b: "strength", c: "dimension", d: "water content" }, answer: "c" },
    { id: 133, text: "A 50 m steel tape that is 0.02 m too long was used to measure the distance between two points A and B. If the measured distance was 160.42 m, calculate the correct distance between A and B.", options: { a: "160.356", b: "160.844", c: "160.484", d: "160.563" }, answer: "c" },
    { id: 134, text: "What percentage of magnesia is allowed in ordinary Portland cement?", options: { a: "0.06", b: "0.1", c: "0.08", d: "0.03" }, answer: "a" },
    { id: 135, text: "Which material were the traditional monuments in Nepal primarily made from?", options: { a: "RCC", b: "Masonry", c: "Timber", d: "Stone" }, answer: "b" },
    { id: 136, text: "According to Bowditch's rule correction to latitude or departure of any side is equal to", options: { a: "total error × (length of side / perimeter)", b: "perimeter × (total error / length of side)", c: "total error in latitude / perimeter of traverse", d: "none of the above." }, answer: "a" },
    { id: 137, text: "Which type of masonry requires the highest level of skill and skilled labor for laying?", options: { a: "Coursed rubble masonry", b: "Ashlar fine masonry", c: "Ashlar chamfered masonry", d: "Dry rubble masonry" }, answer: "d" },
    { id: 138, text: "The apex angle of Dutch cone is about", options: { a: "45°", b: "60°", c: "30°", d: "90°" }, answer: "b" },
    { id: 139, text: "In levelling in continuously sloping ground following data are obtained: 1.32, 2.68, 2.91, 3.2, 1.86, 2.1, 2.5, 2.9, 1.5, 2.2 and 4.8. Select back sighting....", options: { a: "1.32, 1.86, 1.5", b: "1.32, 1.86, 2.2", c: "3.9,2.9,4.8", d: "1.32,2.91,1.86, and so on" }, answer: "a" },
    { id: 141, text: "How many types of brick masonry?", options: { a: "2", b: "4", c: "8", d: "10" }, answer: "b" },
    { id: 142, text: "The phenomenon of slow extension of material at the constant load during tensile test is known as .....", options: { a: "breaking", b: "plasticity", c: "creeping", d: "yielding" }, answer: "c" },
    { id: 143, text: "The characteristics of good quality of bricks are", options: { a: "less water absorption", b: "regular surface", c: "sharp edge", d: "all of the above" }, answer: "d" },
    { id: 144, text: "The centroid of semi-circle about diametric axis (base) is", options: { a: "D/3π", b: "2D/3π", c: "5D/3π", d: "3D/4π" }, answer: "b" },
    { id: 145, text: "The primary purpose of curing is to", options: { a: "reduce the heat loss of concrete that is freshly placed to the atmosphere", b: "reduce the temperature gradient across the cross-section of the concrete", c: "both (a) and (b)", d: "neither (a) nor (b)" }, answer: "c" },
    { id: 146, text: "When the footing is subjected to axial loading and bending moment, then the type of footing is ........", options: { a: "eccentric", b: "concentric", c: "symmetrically loaded", d: "none of the above" }, answer: "a" },
    { id: 147, text: "The latitude and departure of a line AB are +235 m and -135.5 m, respectively. The whole circle bearing of the line AB is", options: { a: "30°", b: "150°", c: "210°", d: "330°" }, answer: "d" },
    { id: 148, text: "Contour interval is", options: { a: "inversely proportional to the scale of the map", b: "directly proportional to the flatness of ground", c: "directly proportional to the time and close", d: "all of the above" }, answer: "a" },
    { id: 149, text: "Which of the following is typically determined by a subtense bar?", options: { a: "Long distance of up to a km", b: "Short distance of up 150 to 200 m", c: "Very short distances of up 50 to 150 m", d: "Very long distances of up to 100 km" }, answer: "b" },
    { id: 150, text: "When a right circular cone is cut parallel with the axis of symmetry, the conic formed is", options: { a: "ellipse", b: "hyperbola", c: "circle", d: "parabola" }, answer: "b" }
];
